export const POST_RERA_PROPERTY_ACTIONS = {
    // Fetch Properties
    FETCH_POST_RERA_PROPERTY_REQUEST: 'FETCH_POST_RERA_PROPERTY_REQUEST',
    FETCH_POST_RERA_PROPERTY_SUCCESS: 'FETCH_POST_RERA_PROPERTY_SUCCESS',
    FETCH_POST_RERA_PROPERTY_FAILURE: 'FETCH_POST_RERA_PROPERTY_FAILURE',

    // Add Property
    ADD_POST_RERA_PROPERTY_REQUEST: 'ADD_POST_RERA_PROPERTY_REQUEST',
    ADD_POST_RERA_PROPERTY_SUCCESS: 'ADD_POST_RERA_PROPERTY_SUCCESS',
    ADD_POST_RERA_PROPERTY_FAILURE: 'ADD_POST_RERA_PROPERTY_FAILURE',

    // Update Property
    UPDATE_POST_RERA_PROPERTY_REQUEST: 'UPDATE_POST_RERA_PROPERTY_REQUEST',
    UPDATE_POST_RERA_PROPERTY_SUCCESS: 'UPDATE_POST_RERA_PROPERTY_SUCCESS',
    UPDATE_POST_RERA_PROPERTY_FAILURE: 'UPDATE_POST_RERA_PROPERTY_FAILURE',

    // Delete Property
    DELETE_POST_RERA_PROPERTY_REQUEST: 'DELETE_POST_RERA_PROPERTY_REQUEST',
    DELETE_POST_RERA_PROPERTY_SUCCESS: 'DELETE_POST_RERA_PROPERTY_SUCCESS',
    DELETE_POST_RERA_PROPERTY_FAILURE: 'DELETE_POST_RERA_PROPERTY_FAILURE',

    // Select Property
    SELECT_POST_RERA_PROPERTY: 'SELECT_POST_RERA_PROPERTY',
    CLEAR_SELECTED_POST_RERA_PROPERTY: 'CLEAR_SELECTED_POST_RERA_PROPERTY',

    // Filters
    SET_POST_RERA_PROPERTY_FILTERS: 'SET_POST_RERA_PROPERTY_FILTERS',
    CLEAR_POST_RERA_PROPERTY_FILTERS: 'CLEAR_POST_RERA_PROPERTY_FILTERS',

    // Clear Error
    CLEAR_ERROR: 'CLEAR_ERROR',
} as const
