export const PRE_LAUNCH_PROPERTY_ACTIONS = {
    // Fetch Properties
    FETCH_PRE_LAUNCH_PROPERTY_REQUEST: 'FETCH_PRE_LAUNCH_PROPERTY_REQUEST',
    FETCH_PRE_LAUNCH_PROPERTY_SUCCESS: 'FETCH_PRE_LAUNCH_PROPERTY_SUCCESS',
    FETCH_PRE_LAUNCH_PROPERTY_FAILURE: 'FETCH_PRE_LAUNCH_PROPERTY_FAILURE',

    // Add Property
    ADD_PRE_LAUNCH_PROPERTY_REQUEST: 'ADD_PRE_LAUNCH_PROPERTY_REQUEST',
    ADD_PRE_LAUNCH_PROPERTY_SUCCESS: 'ADD_PRE_LAUNCH_PROPERTY_SUCCESS',
    ADD_PRE_LAUNCH_PROPERTY_FAILURE: 'ADD_PRE_LAUNCH_PROPERTY_FAILURE',

    // Update Property
    UPDATE_PRE_LAUNCH_PROPERTY_REQUEST: 'UPDATE_PRE_LAUNCH_PROPERTY_REQUEST',
    UPDATE_PRE_LAUNCH_PROPERTY_SUCCESS: 'UPDATE_PRE_LAUNCH_PROPERTY_SUCCESS',
    UPDATE_PRE_LAUNCH_PROPERTY_FAILURE: 'UPDATE_PRE_LAUNCH_PROPERTY_FAILURE',

    // Delete Property
    DELETE_PRE_LAUNCH_PROPERTY_REQUEST: 'DELETE_PRE_LAUNCH_PROPERTY_REQUEST',
    DELETE_PRE_LAUNCH_PROPERTY_SUCCESS: 'DELETE_PRE_LAUNCH_PROPERTY_SUCCESS',
    DELETE_PRE_LAUNCH_PROPERTY_FAILURE: 'DELETE_PRE_LAUNCH_PROPERTY_FAILURE',

    // Select Property
    SELECT_PRE_LAUNCH_PROPERTY: 'SELECT_PRE_LAUNCH_PROPERTY',
    CLEAR_SELECTED_PRE_LAUNCH_PROPERTY: 'CLEAR_SELECTED_PRE_LAUNCH_PROPERTY',

    // Filters
    SET_PRE_LAUNCH_PROPERTY_FILTERS: 'SET_PRE_LAUNCH_PROPERTY_FILTERS',
    CLEAR_PRE_LAUNCH_PROPERTY_FILTERS: 'CLEAR_PRE_LAUNCH_PROPERTY_FILTERS',

    // Clear Error
    CLEAR_ERROR: 'CLEAR_ERROR',
} as const
