// ==================== PROPERTIES ACTION TYPES ====================

// Fetch operations
export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START'
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS'
export const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE'

// Batch fetch operations
export const FETCH_PROPERTIES_BATCH_START = 'FETCH_PROPERTIES_BATCH_START'
export const FETCH_PROPERTIES_BATCH_SUCCESS = 'FETCH_PROPERTIES_BATCH_SUCCESS'
export const FETCH_PROPERTIES_BATCH_FAILURE = 'FETCH_PROPERTIES_BATCH_FAILURE'
export const FETCH_PROPERTIES_BATCH_MORE = 'FETCH_PROPERTIES_BATCH_MORE'

// Single property fetch
export const FETCH_PROPERTY_BY_ID_START = 'FETCH_PROPERTY_BY_ID_START'
export const FETCH_PROPERTY_BY_ID_SUCCESS = 'FETCH_PROPERTY_BY_ID_SUCCESS'
export const FETCH_PROPERTY_BY_ID_FAILURE = 'FETCH_PROPERTY_BY_ID_FAILURE'

// Add property operations
export const ADD_PROPERTY_START = 'ADD_PROPERTY_START'
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS'
export const ADD_PROPERTY_FAILURE = 'ADD_PROPERTY_FAILURE'

// Update property operations
export const UPDATE_PROPERTY_START = 'UPDATE_PROPERTY_START'
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS'
export const UPDATE_PROPERTY_FAILURE = 'UPDATE_PROPERTY_FAILURE'

// Delete property operations
export const DELETE_PROPERTY_START = 'DELETE_PROPERTY_START'
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS'
export const DELETE_PROPERTY_FAILURE = 'DELETE_PROPERTY_FAILURE'

// Utility actions
export const CLEAR_PROPERTIES = 'CLEAR_PROPERTIES'
export const RESET_PROPERTIES_PAGINATION = 'RESET_PROPERTIES_PAGINATION'
