// import type { RentalProperty } from '../../data_types/restack/restack-rental'

export const rentalPropertiesDummyData: any[] = [
    {
        id: '1',
        projectName: 'Rental Project 1',
        configuration: '1BHK',
        propertyType: 'Apartment',
        builtUpArea: 600,
        carpetArea: 400,
        micromarket: 'Location 1',
        address: 'Address 1',
        price: 10000,
        furnishingStatus: 'Unfurnished',
        ageOfProperty: '1-5 years',
        postedOn: 1672531200,
        postedBy: 'Owner',
        propertyId: 'RP1',
        url: 'http://example.com/rp1',
        description: 'Description 1',
        amenities: ['Gym', 'Swimming Pool'],
        images: ['image1.jpg', 'image2.jpg'],
        contactDetails: {
            name: 'John Doe',
            phone: '123-456-7890',
            email: 'john.doe@example.com',
        },
        listingStatus: 'active',
        deposit: 20000,
        maintenance: 1000,
        availableFrom: 1675219200,
        preferredTenant: 'Family',
        parkingAvailable: true,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '2',
        projectName: 'Rental Project 2',
        configuration: '2BHK',
        propertyType: 'House',
        builtUpArea: 1200,
        carpetArea: 900,
        micromarket: 'Location 2',
        address: 'Address 2',
        price: 15000,
        furnishingStatus: 'Semi-Furnished',
        ageOfProperty: '5-10 years',
        postedOn: 1675219200,
        postedBy: 'Broker',
        propertyId: 'RP2',
        url: 'http://example.com/rp2',
        description: 'Description 2',
        amenities: ['Garden', 'Parking'],
        images: ['image3.jpg', 'image4.jpg'],
        contactDetails: {
            name: 'Jane Smith',
            phone: '987-654-3210',
            email: 'jane.smith@example.com',
        },
        listingStatus: 'inactive',
        deposit: 30000,
        maintenance: 1500,
        availableFrom: 1677811200,
        preferredTenant: 'Couple',
        parkingAvailable: false,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '3',
        projectName: 'Rental Project 3',
        configuration: '3BHK',
        propertyType: 'Condo',
        builtUpArea: 1800,
        carpetArea: 1400,
        micromarket: 'Location 3',
        address: 'Address 3',
        price: 20000,
        furnishingStatus: 'Furnished',
        ageOfProperty: '10+ years',
        postedOn: 1677811200,
        postedBy: 'Owner',
        propertyId: 'RP3',
        url: 'http://example.com/rp3',
        description: 'Description 3',
        amenities: ['Security', 'Clubhouse'],
        images: ['image5.jpg', 'image6.jpg'],
        contactDetails: {
            name: 'Peter Jones',
            phone: '456-789-0123',
            email: 'peter.jones@example.com',
        },
        listingStatus: 'rented',
        deposit: 40000,
        maintenance: 2000,
        availableFrom: 1680316800,
        preferredTenant: 'Family',
        parkingAvailable: true,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '4',
        projectName: 'Rental Project 4',
        configuration: '1BHK',
        propertyType: 'Apartment',
        builtUpArea: 600,
        carpetArea: 400,
        micromarket: 'Location 4',
        address: 'Address 4',
        price: 12000,
        furnishingStatus: 'Unfurnished',
        ageOfProperty: 'New Construction',
        postedOn: 1680316800,
        postedBy: 'Broker',
        propertyId: 'RP4',
        url: 'http://example.com/rp4',
        description: 'Description 4',
        amenities: ['Gym', 'Swimming Pool'],
        images: ['image7.jpg', 'image8.jpg'],
        contactDetails: {
            name: 'Alice Brown',
            phone: '789-012-3456',
            email: 'alice.brown@example.com',
        },
        listingStatus: 'active',
        deposit: 24000,
        maintenance: 1200,
        availableFrom: 1682908800,
        preferredTenant: 'Singles',
        parkingAvailable: false,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '5',
        projectName: 'Rental Project 5',
        configuration: '2BHK',
        propertyType: 'House',
        builtUpArea: 1200,
        carpetArea: 900,
        micromarket: 'Location 5',
        address: 'Address 5',
        price: 17000,
        furnishingStatus: 'Semi-Furnished',
        ageOfProperty: '1-5 years',
        postedOn: 1682908800,
        postedBy: 'Owner',
        propertyId: 'RP5',
        url: 'http://example.com/rp5',
        description: 'Description 5',
        amenities: ['Garden', 'Parking'],
        images: ['image9.jpg', 'image10.jpg'],
        contactDetails: {
            name: 'Bob Wilson',
            phone: '234-567-8901',
            email: 'bob.wilson@example.com',
        },
        listingStatus: 'inactive',
        deposit: 34000,
        maintenance: 1700,
        availableFrom: 1685587200,
        preferredTenant: 'Couple',
        parkingAvailable: true,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '6',
        projectName: 'Rental Project 6',
        configuration: '3BHK',
        propertyType: 'Condo',
        builtUpArea: 1800,
        carpetArea: 1400,
        micromarket: 'Location 6',
        address: 'Address 6',
        price: 22000,
        furnishingStatus: 'Furnished',
        ageOfProperty: '5-10 years',
        postedOn: 1685587200,
        postedBy: 'Broker',
        propertyId: 'RP6',
        url: 'http://example.com/rp6',
        description: 'Description 6',
        amenities: ['Security', 'Clubhouse'],
        images: ['image11.jpg', 'image12.jpg'],
        contactDetails: {
            name: 'Cathy Davis',
            phone: '567-890-1234',
            email: 'cathy.davis@example.com',
        },
        listingStatus: 'rented',
        deposit: 44000,
        maintenance: 2200,
        availableFrom: 1688179200,
        preferredTenant: 'Family',
        parkingAvailable: false,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '7',
        projectName: 'Rental Project 7',
        configuration: '1BHK',
        propertyType: 'Apartment',
        builtUpArea: 650,
        carpetArea: 450,
        micromarket: 'Location 7',
        address: 'Address 7',
        price: 11000,
        furnishingStatus: 'Unfurnished',
        ageOfProperty: '10+ years',
        postedOn: 1688179200,
        postedBy: 'Owner',
        propertyId: 'RP7',
        url: 'http://example.com/rp7',
        description: 'Description 7',
        amenities: ['Gym', 'Swimming Pool', 'Parking'],
        images: ['image13.jpg', 'image14.jpg'],
        contactDetails: {
            name: 'David White',
            phone: '890-123-4567',
            email: 'david.white@example.com',
        },
        listingStatus: 'active',
        deposit: 22000,
        maintenance: 1100,
        availableFrom: 1690857600,
        preferredTenant: 'Singles',
        parkingAvailable: true,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '8',
        projectName: 'Rental Project 8',
        configuration: '2BHK',
        propertyType: 'House',
        builtUpArea: 1250,
        carpetArea: 950,
        micromarket: 'Location 8',
        address: 'Address 8',
        price: 16000,
        furnishingStatus: 'Semi-Furnished',
        ageOfProperty: 'New Construction',
        postedOn: 1690857600,
        postedBy: 'Broker',
        propertyId: 'RP8',
        url: 'http://example.com/rp8',
        description: 'Description 8',
        amenities: ['Garden', 'Security'],
        images: ['image15.jpg', 'image16.jpg'],
        contactDetails: {
            name: 'Emily Green',
            phone: '345-678-9012',
            email: 'emily.green@example.com',
        },
        listingStatus: 'inactive',
        deposit: 32000,
        maintenance: 1600,
        availableFrom: 1693536000,
        preferredTenant: 'Couple',
        parkingAvailable: false,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '9',
        projectName: 'Rental Project 9',
        configuration: '3BHK',
        propertyType: 'Condo',
        builtUpArea: 1850,
        carpetArea: 1450,
        micromarket: 'Location 9',
        address: 'Address 9',
        price: 21000,
        furnishingStatus: 'Furnished',
        ageOfProperty: '1-5 years',
        postedOn: 1693536000,
        postedBy: 'Owner',
        propertyId: 'RP9',
        url: 'http://example.com/rp9',
        description: 'Description 9',
        amenities: ['Security', 'Clubhouse', 'Gym'],
        images: ['image17.jpg', 'image18.jpg'],
        contactDetails: {
            name: 'Frank Black',
            phone: '678-901-2345',
            email: 'frank.black@example.com',
        },
        listingStatus: 'rented',
        deposit: 42000,
        maintenance: 2100,
        availableFrom: 1696214400,
        preferredTenant: 'Family',
        parkingAvailable: true,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '10',
        projectName: 'Rental Project 10',
        configuration: '4BHK',
        propertyType: 'Villa',
        builtUpArea: 2500,
        carpetArea: 2000,
        micromarket: 'Location 10',
        address: 'Address 10',
        price: 30000,
        furnishingStatus: 'Furnished',
        ageOfProperty: '5-10 years',
        postedOn: 1696214400,
        postedBy: 'Broker',
        propertyId: 'RP10',
        url: 'http://example.com/rp10',
        description: 'Description 10',
        amenities: ['Swimming Pool', 'Garden', 'Parking', 'Security'],
        images: ['image19.jpg', 'image20.jpg'],
        contactDetails: {
            name: 'Grace Taylor',
            phone: '901-234-5678',
            email: 'grace.taylor@example.com',
        },
        listingStatus: 'active',
        deposit: 60000,
        maintenance: 3000,
        availableFrom: 1698892800,
        preferredTenant: 'Executives',
        parkingAvailable: true,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '11',
        projectName: 'Rental Project 11',
        configuration: '1BHK',
        propertyType: 'Apartment',
        builtUpArea: 700,
        carpetArea: 500,
        micromarket: 'Location 11',
        address: 'Address 11',
        price: 13000,
        furnishingStatus: 'Unfurnished',
        ageOfProperty: 'New Construction',
        postedOn: 1698892800,
        postedBy: 'Owner',
        propertyId: 'RP11',
        url: 'http://example.com/rp11',
        description: 'Description 11',
        amenities: ['Gym', 'Swimming Pool'],
        images: ['image21.jpg', 'image22.jpg'],
        contactDetails: {
            name: 'Harry Clark',
            phone: '234-567-8901',
            email: 'harry.clark@example.com',
        },
        listingStatus: 'inactive',
        deposit: 26000,
        maintenance: 1300,
        availableFrom: 1701571200,
        preferredTenant: 'Singles',
        parkingAvailable: false,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '12',
        projectName: 'Rental Project 12',
        configuration: '2BHK',
        propertyType: 'House',
        builtUpArea: 1300,
        carpetArea: 1000,
        micromarket: 'Location 12',
        address: 'Address 12',
        price: 18000,
        furnishingStatus: 'Semi-Furnished',
        ageOfProperty: '1-5 years',
        postedOn: 1701571200,
        postedBy: 'Broker',
        propertyId: 'RP12',
        url: 'http://example.com/rp12',
        description: 'Description 12',
        amenities: ['Garden', 'Parking'],
        images: ['image23.jpg', 'image24.jpg'],
        contactDetails: {
            name: 'Ivy Lewis',
            phone: '567-890-1234',
            email: 'ivy.lewis@example.com',
        },
        listingStatus: 'rented',
        deposit: 36000,
        maintenance: 1800,
        availableFrom: 1704163200,
        preferredTenant: 'Couple',
        parkingAvailable: true,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '13',
        projectName: 'Rental Project 13',
        configuration: '3BHK',
        propertyType: 'Condo',
        builtUpArea: 1900,
        carpetArea: 1500,
        micromarket: 'Location 13',
        address: 'Address 13',
        price: 23000,
        furnishingStatus: 'Furnished',
        ageOfProperty: '5-10 years',
        postedOn: 1704163200,
        postedBy: 'Owner',
        propertyId: 'RP13',
        url: 'http://example.com/rp13',
        description: 'Description 13',
        amenities: ['Security', 'Clubhouse', 'Swimming Pool'],
        images: ['image25.jpg', 'image26.jpg'],
        contactDetails: {
            name: 'Jack Martin',
            phone: '890-123-4567',
            email: 'jack.martin@example.com',
        },
        listingStatus: 'active',
        deposit: 46000,
        maintenance: 2300,
        availableFrom: 1706755200,
        preferredTenant: 'Family',
        parkingAvailable: false,
        petsAllowed: false,
        listedBy: 'Owner',
    },
    {
        id: '14',
        projectName: 'Rental Project 14',
        configuration: '4BHK',
        propertyType: 'Villa',
        builtUpArea: 2600,
        carpetArea: 2100,
        micromarket: 'Location 14',
        address: 'Address 14',
        price: 32000,
        furnishingStatus: 'Furnished',
        ageOfProperty: '10+ years',
        postedOn: 1706755200,
        postedBy: 'Broker',
        propertyId: 'RP14',
        url: 'http://example.com/rp14',
        description: 'Description 14',
        amenities: ['Swimming Pool', 'Garden', 'Parking', 'Security', 'Gym'],
        images: ['image27.jpg', 'image28.jpg'],
        contactDetails: {
            name: 'Kelly Nash',
            phone: '234-567-8901',
            email: 'kelly.nash@example.com',
        },
        listingStatus: 'inactive',
        deposit: 64000,
        maintenance: 3200,
        availableFrom: 1709433600,
        preferredTenant: 'Executives',
        parkingAvailable: true,
        petsAllowed: true,
        listedBy: 'Broker',
    },
    {
        id: '15',
        projectName: 'Rental Project 15',
        configuration: '1BHK',
        propertyType: 'Apartment',
        builtUpArea: 750,
        carpetArea: 550,
        micromarket: 'Location 15',
        address: 'Address 15',
        price: 14000,
        furnishingStatus: 'Unfurnished',
        ageOfProperty: 'New Construction',
        postedOn: 1709433600,
        postedBy: 'Owner',
        propertyId: 'RP15',
        url: 'http://example.com/rp15',
        description: 'Description 15',
        amenities: ['Gym', 'Swimming Pool'],
        images: ['image29.jpg', 'image30.jpg'],
        contactDetails: {
            name: 'Liam Owen',
            phone: '567-890-1234',
            email: 'liam.owen@example.com',
        },
        listingStatus: 'rented',
        deposit: 28000,
        maintenance: 1400,
        availableFrom: 1712112000,
        preferredTenant: 'Singles',
        parkingAvailable: false,
        petsAllowed: false,
        listedBy: 'Owner',
    },
]
